name: CI  # Workflow 名稱

on:       # 何時會觸發
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:     # 實際會執行什麼工作
  test:
    name: test (${{ matrix.python-version }})
    runs-on: ubuntu-latest         # 在怎樣的設備上運行

    strategy:
      matrix:
        python-version: ["3.10","3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: "true"
          # Glob pattern to match files relative to the repository root to control the cache
          cache-dependency-glob: |
            **/*requirements*.txt
            **/*requirements*.in
            **/*constraints*.txt
            **/*constraints*.in
            **/pyproject.toml
            **/uv.lock
            **/*.py.lock

          # Whether to restore the cache if found
          restore-cache: "true"

          # Whether to save the cache after the run
          save-cache: "true"


      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{matrix.python-version}}

      # - name: Debug cache key
      #   run: |
      #     echo "OS: ${{ runner.os }}"
      #     echo "Python: ${{ matrix.python-version }}"
      #     echo "Lock hash: ${{ hashFiles('uv.lock') }}"
      #     echo "Cache key: uv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('uv.lock') }}"

      # - name: Create uv cache dir
      #   run: mkdir -p ~/.cache/uv

      # - name: Cache uv
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/uv
      #     key: uv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('uv.lock') }}

      # - name: Show cache status
      #   run: echo "Cache hit = ${{ steps.cache-uv.outputs.cache-hit }}"


      - name: Sync dependencies
        run: uv sync --frozen

      - name: Run tests and coverage
        run: uv run pytest --cov=app --cov-fail-under=80 --cov-report=html

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Run ruff
        run: uv run ruff check .

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/


  test-summary:
    name: test
    runs-on: ubuntu-latest

    needs: test
    if: ${{ success() }}


    steps:
      - run: echo "All matrix tests passed"
