name: CI  # Workflow 名稱

on:       # 何時會觸發
  push:
    branches: [ main ]
  pull_request:

jobs:     # 實際會執行什麼工作
  test:
    runs-on: ubuntu-latest         # 在怎樣的設備上運行

    steps:                         # 在怎樣的設備上運行
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Run tests and coverage
        run: uv run pytest --cov=app --cov-fail-under=80

      - name: Run ruff
        run: uv run ruff check .